FROM    ubuntu:16.04
MAINTAINER  Pedro Alves <palves@pentaho.com>

# Set the locale

ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 
ENV TERM xterm

# For jdk7, install oracle-java7-installer
# For jdk8, install oracle-java8-installer

RUN sed 's/main$/main universe/' -i /etc/apt/sources.list && \
    apt-get update && apt-get install -y software-properties-common apt-transport-https ca-certificates iputils-ping curl unzip git lftp sudo && \
		curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -  && \		
		add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    # DISABLED - Oracle removed java7 from pub site :( # apt-get install -y oracle-java7-installer && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y docker-ce oracle-java8-installer && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*
    

