FROM foundry-core
MAINTAINER  Pedro Alves <palves@pentaho.com>

ADD scripts/run.sh /opt/lumada/
ADD tmp/lumada/ /opt/lumada/

RUN cd /opt/lumada && \
	tar -xvf ./*tgz -C . && \
	./*/bin/install
	echo DONE!

WORKDIR /opt/lumada


EXPOSE 8080 8044 9001

# 1. Run 

ENTRYPOINT ["bash", "/opt/lumada/run.sh"]

